-- Create the inventory table in your Supabase project.
-- 1. Go to your Supabase project dashboard.
-- 2. Click on "SQL Editor" in the left sidebar.
-- 3. Click "New query".
-- 4. Copy and paste the following SQL code into the editor.
-- 5. Click "Run".

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stencil TEXT,
    orientation TEXT,
    invoice_number TEXT,
    cone_size TEXT,
    number_of_lines TEXT,
    misc_info TEXT,
    date_of_inventory TEXT,
    silkscreen TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
